// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3uuh9avm5oL2wiA7blf4b1UqyWhHSQw',
    appId: '1:959065629859:web:6dbc5ababf9591954d8b16',
    messagingSenderId: '959065629859',
    projectId: 'myfinnsindbin-b59c7',
    authDomain: 'myfinnsindbin-b59c7.firebaseapp.com',
    storageBucket: 'myfinnsindbin-b59c7.firebasestorage.app',
    measurementId: 'G-T3JJ7F9FVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjovXhgYPUhoIDoRc9_4eNcdZne0Fb1g',
    appId: '1:959065629859:android:4d6eab433df5aa834d8b16',
    messagingSenderId: '959065629859',
    projectId: 'myfinnsindbin-b59c7',
    storageBucket: 'myfinnsindbin-b59c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7vlb_p_TaFk9a0C0gDOAuVxTjAJWnKA',
    appId: '1:959065629859:ios:b250b7ad7ffd7a314d8b16',
    messagingSenderId: '959065629859',
    projectId: 'myfinnsindbin-b59c7',
    storageBucket: 'myfinnsindbin-b59c7.firebasestorage.app',
    iosBundleId: 'com.example.myfin',
  );
}
